name: Pi Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          -f ~/Documents/docker/website/
          docker compose up -d --build frontend