name: Pi Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          rsync -av --exclude='.git' . /home/runner/deployment_inbox/frontend/
          docker compose -p website-project -f /home/runner/deployment_inbox/docker-compose.yml up -d --build --remove-orphans frontend